# Generated by Django 3.2.7 on 2022-05-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol_Usuario',
            fields=[
                ('cod_rol_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('nombres_del_usuario', models.CharField(max_length=45)),
                ('apellidos_del_usuario', models.CharField(max_length=45)),
                ('direccion_email', models.CharField(max_length=60)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
