# Generated by Django 3.2.7 on 2022-05-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0002_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('cod_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=1)),
                ('datos_viejos', models.CharField(max_length=5000)),
                ('datos_nuevos', models.CharField(max_length=5000)),
                ('usuario', models.CharField(max_length=45)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria_Sesiones',
            fields=[
                ('cod_aud_sesiones', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField()),
                ('informacion', models.CharField(max_length=500)),
            ],
        ),
    ]
