# Generated by Django 3.2.7 on 2022-05-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0004_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Facultad',
            fields=[
                ('cod_usuario_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_facultad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.facultad')),
                ('cod_usuario_rol', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.usuario_rol')),
            ],
        ),
    ]
