# Generated by Django 3.2.7 on 2022-05-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0005_usuario_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_rol',
            name='cod_facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.facultad'),
        ),
        migrations.DeleteModel(
            name='Usuario_Facultad',
        ),
    ]
