# Generated by Django 3.2.7 on 2022-05-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0007_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_rol',
            name='cod_facultad',
        ),
        migrations.AddField(
            model_name='usuario_rol',
            name='cod_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.carrera'),
        ),
    ]
