# Generated by Django 3.2.7 on 2022-05-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0008_auto_20220519_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='cod_faculad',
            new_name='cod_facultad',
        ),
    ]
