# Generated by Django 3.2.7 on 2022-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0009_rename_cod_faculad_carrera_cod_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('cod_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
