# Generated by Django 3.2.7 on 2022-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0010_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='estado',
            field=models.IntegerField(null=True),
        ),
    ]
