# Generated by Django 3.2.7 on 2022-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0011_semestre_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('cod_plan_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='semestre',
            name='alta_fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='semestre',
            name='alta_usuario',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='semestre',
            name='modif_fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='semestre',
            name='modif_usuario',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
