# Generated by Django 3.2.7 on 2022-05-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0012_auto_20220521_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_estudio',
            name='cod_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.carrera'),
        ),
    ]
