# Generated by Django 3.2.7 on 2022-05-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0014_carrera_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('cod_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('horas_catedra', models.IntegerField()),
                ('curso', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_carrera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.carrera')),
                ('cod_plan_estudio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.plan_estudio')),
                ('cod_semestre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.semestre')),
            ],
        ),
    ]
