# Generated by Django 3.2.7 on 2022-05-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0015_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura_Usuario',
            fields=[
                ('cod_asignatura_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_asignatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.asignatura')),
                ('cod_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.usuario')),
            ],
        ),
    ]
