# Generated by Django 3.2.7 on 2022-05-23 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0016_asignatura_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura_usuario',
            name='cod_usuario',
        ),
        migrations.AddField(
            model_name='asignatura_usuario',
            name='cod_usuario_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.usuario_rol'),
        ),
    ]
