# Generated by Django 3.2.7 on 2022-05-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0017_auto_20220523_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='semestre',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
