# Generated by Django 3.2.7 on 2022-06-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0018_auto_20220530_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Clase',
            fields=[
                ('cod_tipo_clase', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
