# Generated by Django 3.2.7 on 2022-06-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0019_tipo_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad_Aprendizaje',
            fields=[
                ('cod_unidad_aprendizaje', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_asignatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.asignatura')),
            ],
        ),
    ]
