# Generated by Django 3.2.7 on 2022-06-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0020_unidad_aprendizaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('cod_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_unidad_aprendizaje', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.unidad_aprendizaje')),
            ],
        ),
    ]
