# Generated by Django 3.2.7 on 2022-06-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0026_trabajo_autonomo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera_Planilla',
            fields=[
                ('cod_cabecera_planilla', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_clase', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('fecha_vencimiento', models.DateField()),
                ('evaluacion', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_asignatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.asignatura')),
                ('cod_tipo_clase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.tipo_clase')),
                ('cod_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_Utilizados',
            fields=[
                ('cod_trabajos_utilizados', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_cabecera_planilla', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.cabecera_planilla')),
                ('cod_trabajo_autonomo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.trabajo_autonomo')),
            ],
        ),
        migrations.CreateModel(
            name='Recursos_Utilizados',
            fields=[
                ('cod_recursos_utilizados', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_cabecera_planilla', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.cabecera_planilla')),
                ('cod_recurso_auxiliar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.recursos_auxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='Metodologia_Utilizada',
            fields=[
                ('cod_metodologia_utilizada', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_cabecera_planilla', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.cabecera_planilla')),
                ('cod_metodologia_enseñanza', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.metodologia_enseñanza')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('cod_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_cabecera_planilla', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.cabecera_planilla')),
                ('cod_instrumento_evaluacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.instrumento_evaluacion')),
                ('cod_tipo_eva', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.tipo_eva')),
            ],
        ),
        migrations.CreateModel(
            name='Contenidos_Dados',
            fields=[
                ('cod_contenidos_dados', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
                ('cod_cabecera_planilla', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.cabecera_planilla')),
                ('cod_contenido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.contenido')),
            ],
        ),
    ]
