# Generated by Django 3.2.7 on 2022-06-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoducWeb', '0027_cabecera_planilla_contenidos_dados_evaluaciones_metodologia_utilizada_recursos_utilizados_trabajos_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecera_planilla',
            name='cod_tipo_clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoducWeb.tipo_clase'),
        ),
    ]
